version: "3.8"
services:
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    ports:
      - "8082:80"
    environment:
      - JWT_ENABLED=false
