# Generated by Django 5.2.9 on 2026-03-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee')),
            ],
            options={
                'verbose_name': 'Harakat',
                'verbose_name_plural': 'Harakatlar',
                'db_table': 'auditLog',
            },
        ),
    ]
