# Generated by Django 5.2.9 on 2025-12-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Harakat', 'verbose_name_plural': 'Harakatlar'},
        ),
    ]
