# Generated by Django 5.2.9 on 2026-06-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_options_alter_auditlog_description_and_more'),
        ('main', '0028_alter_department_name_alter_directorate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEmployeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinfl', models.CharField(blank=True, default='', max_length=20)),
                ('full_name', models.CharField(blank=True, default='', max_length=300)),
                ('result', models.CharField(choices=[('updated', 'Yangilandi'), ('blocked', 'Bloklandi'), ('error', 'Xato')], db_index=True, max_length=20)),
                ('changes', models.TextField(blank=True, default='')),
                ('error_msg', models.TextField(blank=True, default='')),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee')),
            ],
            options={
                'verbose_name': 'Xodim sync yozuvi',
                'verbose_name_plural': 'Xodim sync yozuvlari',
                'db_table': 'syncemployeelog',
                'ordering': ['-date_creat'],
            },
        ),
    ]
