# Generated by Django 5.2.9 on 2026-06-04 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_syncemployeelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('blocked', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Sekundlarda')),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('partial', 'Qisman xato'), ('failed', 'Xatolik')], default='success', max_length=20)),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sync natijasi',
                'verbose_name_plural': 'Sync natijalari',
                'db_table': 'synclog',
                'ordering': ['-date_creat'],
            },
        ),
        migrations.AddField(
            model_name='syncemployeelog',
            name='sync',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_logs', to='core.synclog'),
            preserve_default=False,
        ),
    ]
