# Generated by Django 5.2.9 on 2026-08-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_synclog_syncemployeelog_sync'),
        ('main', '0070_alter_employee_options_alter_material_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=1000, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=300, null=True)),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='main.employee')),
            ],
            options={
                'verbose_name': 'Push obunasi',
                'verbose_name_plural': 'Push obunalari',
                'db_table': 'push_subscription',
            },
        ),
    ]
