# Generated by Django 5.2.9 on 2026-10-06 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pushsubscription'),
        ('main', '0092_deed_signer_can_add_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1024, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=10)),
                ('device_name', models.CharField(blank=True, default='', max_length=100)),
                ('app_version', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to='main.employee')),
            ],
            options={
                'verbose_name': 'Mobil qurilma',
                'verbose_name_plural': 'Mobil qurilmalar',
                'db_table': 'mobile_device',
            },
        ),
    ]
