# Generated by Django 5.2.9 on 2026-09-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_attachment_message_deleted_at_and_more'),
        ('main', '0091_remove_old_goal_receiver_matcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_conversations', to='main.employee'),
        ),
    ]
