# Generated by Django 5.2.9 on 2026-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_hidden_for'),
        ('main', '0091_remove_old_goal_receiver_matcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Guruh nomi'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='group_conversations', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('direct', 'Shaxsiy suhbat'), ('ai', 'AI Yordamchi'), ('group', 'Guruh')], db_index=True, default='direct', max_length=10),
        ),
    ]
