# Generated by Django 5.2.9 on 2026-09-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_name_conversation_participants_and_more'),
        ('main', '0091_remove_old_goal_receiver_matcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='chat_admin_groups', to='main.employee'),
        ),
    ]
