# Generated by Django 5.2.9 on 2026-09-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('direct', 'Shaxsiy suhbat'), ('ai', 'AI Yordamchi'), ('group', 'Guruh'), ('saved', 'Saqlangan xabarlar')], db_index=True, default='direct', max_length=10),
        ),
    ]
