# Generated by Django 5.2.9 on 2026-10-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_conversation_kind'),
        ('main', '0092_deed_signer_can_add_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_attachment',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.CreateModel(
            name='ConversationClear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clears', to='chat.conversation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_clears', to='main.employee')),
            ],
            options={
                'verbose_name': 'Suhbat tozalangan vaqt',
                'verbose_name_plural': 'Suhbat tozalangan vaqtlar',
                'db_table': 'chat_conversation_clear',
                'constraints': [models.UniqueConstraint(fields=('conversation', 'employee'), name='uniq_chat_clear_conv_employee')],
            },
        ),
    ]
