# Generated by Django 5.2.9 on 2026-10-09 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_soft_delete_and_clear'),
        ('main', '0099_backfill_deed_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('agenda', models.TextField(blank=True, default='')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('zoom_id', models.CharField(blank=True, default='', max_length=30)),
                ('join_url', models.URLField(blank=True, default='', max_length=500)),
                ('start_url', models.TextField(blank=True, default='')),
                ('password', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='scheduled', max_length=10)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings_organized', to='main.employee')),
                ('participants', models.ManyToManyField(blank=True, related_name='meetings_invited', to='main.employee')),
            ],
            options={
                'verbose_name': 'Uchrashuv',
                'verbose_name_plural': 'Uchrashuvlar',
                'db_table': 'chat_meeting',
                'ordering': ['start_at'],
            },
        ),
    ]
