# Generated by Django 5.2.9 on 2026-10-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('cancelled', 'Bekor qilingan'), ('finished', 'Tugatilgan')], db_index=True, default='scheduled', max_length=10),
        ),
    ]
