# Generated by Django 5.2.9 on 2026-10-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_meeting_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['start_at'], 'verbose_name': 'Uchrashuv', 'verbose_name_plural': 'Zoom'},
        ),
    ]
