# Generated by Django 5.2.9 on 2025-12-12 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deedconsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('viewed', 'Kutulmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='viewed', max_length=20)),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('deed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.deed')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
    ]
