# Generated by Django 5.2.9 on 2026-04-01 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_missing_rol_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_user', to='main.employee'),
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='given',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='full',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
