# Generated by Django 5.2.9 on 2025-12-12 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_deedconsent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deedconsent',
            old_name='receiver',
            new_name='employee',
        ),
    ]
