# Generated by Django 5.2.9 on 2025-12-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_receiver_deedconsent_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deedconsent',
            table='deedconsent',
        ),
    ]
