# Generated by Django 5.2.9 on 2026-04-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_goal_organization_order_organization_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('viewed', 'Yangi'), ('process', 'Jarayonda'), ('finished', 'Yakunlandi'), ('approved', 'Tasdiqlandi'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], db_index=True, default='viewed', max_length=20),
        ),
    ]
