# Generated by Django 5.2.9 on 2026-03-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='organization',
        ),
    ]
