# Generated by Django 5.2.9 on 2025-12-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_deedconsent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedconsent',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deed',
            name='message_receiver',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deed',
            name='message_sender',
            field=models.TextField(blank=True, null=True),
        ),
    ]
