# Generated by Django 5.2.9 on 2026-04-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('viewed', 'Yangi'), ('process', 'Jarayonda'), ('finished', 'Tayyorlandi'), ('approved', 'Tasdiqlandi'), ('accepted', 'Qabul qilindi'), ('canceled', 'Bekor qilindi'), ('rejected', 'Rad etildi')], db_index=True, default='viewed', max_length=20),
        ),
    ]
