# Generated by Django 5.2.9 on 2025-12-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_deedconsent_message_alter_deed_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pinfil',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
