# Generated by Django 5.2.9 on 2026-03-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_materialuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Uskuna kategoriyasi', 'verbose_name_plural': 'Uskuna kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Shartnoma', 'verbose_name_plural': 'Shartnomalar'},
        ),
        migrations.AlterModelOptions(
            name='deed',
            options={'verbose_name': 'Xujat', 'verbose_name_plural': 'Xujatlar'},
        ),
        migrations.AlterModelOptions(
            name='deedconsent',
            options={'verbose_name': 'Xujat kelishuvchisi', 'verbose_name_plural': 'Xujat kelishuvchilari'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departament', 'verbose_name_plural': 'Departamentlar'},
        ),
        migrations.AlterModelOptions(
            name='directorate',
            options={'verbose_name': 'Boshqarma', 'verbose_name_plural': 'Boshqarmalar'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Ariza kategoriyasi', 'verbose_name_plural': 'Ariza kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Uskuna turi', 'verbose_name_plural': 'Uskuna turlari'},
        ),
        migrations.AlterModelOptions(
            name='liable',
            options={'verbose_name': 'Shartnomaga javobgar shaxs', 'verbose_name_plural': 'Shartnomaga javobgar shaxslar'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiallar'},
        ),
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'verbose_name': 'Material kategoriyasi', 'verbose_name_plural': 'Material kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='materialuser',
            options={'verbose_name': 'Material user', 'verbose_name_plural': 'Material userlar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterModelOptions(
            name='ordermaterial',
            options={'verbose_name': 'Ariza materiali', 'verbose_name_plural': 'Arizalar materiallari'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlar'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Xudud', 'verbose_name_plural': 'Xududlar'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Rollar'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Qurulma', 'verbose_name_plural': 'Qurulmalar'},
        ),
        migrations.AlterModelOptions(
            name='structurecategory',
            options={'verbose_name': 'Qurulma kategoriyasi', 'verbose_name_plural': 'Qurulma kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='technics',
            options={'verbose_name': 'Uskuna', 'verbose_name_plural': 'Uskunalar'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Material birligi', 'verbose_name_plural': 'Material birliglari'},
        ),
        migrations.AlterModelTable(
            name='materialuser',
            table='materialuser',
        ),
    ]
