# Generated by Django 5.2.9 on 2026-04-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_process',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
