# Generated by Django 5.2.9 on 2026-04-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='confirm',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
