# Generated by Django 5.2.9 on 2026-04-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_date_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_canceled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
