# Generated by Django 5.2.9 on 2025-12-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_employee_pinfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='pinfil',
        ),
    ]
