# Generated by Django 5.2.9 on 2025-12-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_employee_pinfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
    ]
