# Generated by Django 5.2.9 on 2026-04-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rol_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='temp_fix',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
