# Generated by Django 5.2.9 on 2026-04-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_date_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sender_seen',
            field=models.BooleanField(default=False),
        ),
    ]
