# Generated by Django 5.2.9 on 2026-03-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaterial',
            name='given',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
