# Generated by Django 5.2.9 on 2025-12-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_employee_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='deed',
            options={'verbose_name': 'Akt', 'verbose_name_plural': 'Aktlar'},
        ),
        migrations.AlterModelOptions(
            name='deedconsent',
            options={'verbose_name': 'Akt_kelishuvchi', 'verbose_name_plural': 'Akt_kelishuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departament', 'verbose_name_plural': 'Departamentlar'},
        ),
        migrations.AlterModelOptions(
            name='directorate',
            options={'verbose_name': 'Boshqarma', 'verbose_name_plural': 'Boshqarmalar'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Maqsad', 'verbose_name_plural': 'Maqsadlar'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'material', 'verbose_name_plural': 'materiallar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zayafka', 'verbose_name_plural': 'Zayafkalar'},
        ),
        migrations.AlterModelOptions(
            name='ordermaterial',
            options={'verbose_name': 'Zayafka_material', 'verbose_name_plural': 'Zayafka_materiallar'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlar'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Lavozim', 'verbose_name_plural': 'Lavozimlar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Mintaqa', 'verbose_name_plural': 'Mintaqalar'},
        ),
        migrations.AlterModelOptions(
            name='technics',
            options={'verbose_name': 'Texnika', 'verbose_name_plural': 'Texnikalar'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Mavzu', 'verbose_name_plural': 'Mavzular'},
        ),
        migrations.AddField(
            model_name='employee',
            name='pinfil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
