# Generated by Django 5.2.9 on 2026-04-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_sender_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_seen',
            field=models.BooleanField(default=False),
        ),
    ]
