# Generated by Django 5.2.9 on 2026-04-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_user_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deed',
            name='receiver_seen',
        ),
        migrations.RemoveField(
            model_name='deed',
            name='sender_seen',
        ),
    ]
