# Generated by Django 5.2.9 on 2026-03-31 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ordermaterial_given'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='client',
            new_name='confirm',
        ),
    ]
