# Generated by Django 5.2.9 on 2025-12-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_category_options_alter_deed_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='pinfil',
            new_name='pinfl',
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
