# Generated by Django 5.2.9 on 2025-12-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_pinfil_employee_pinfl_employee_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deed',
            name='status',
            field=models.CharField(choices=[('viewed', 'Kutulmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='viewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='deedconsent',
            name='status',
            field=models.CharField(choices=[('viewed', 'Kutulmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='viewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pinfl',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('client', 'Mijoz'), ('worker', 'IVS xodimi')], db_index=True, default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('free', "Bo'sh"), ('repair', 'Ta’mirda'), ('defect', 'Brak')], db_index=True, default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('viewed', 'Kutulmoqda'), ('accepted', 'Qabul qilindi'), ('finished', 'Yakunlandi'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='viewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_work',
            field=models.CharField(choices=[('online', 'onlayin'), ('offline', 'oflayin')], db_index=True, default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('IMV', 'IMV'), ('PENSIYA', 'PENSIYA'), ('GAZNA', "G'azna"), ('IVS', 'IVS')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='technics',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('free', "Bo'sh"), ('repair', 'Ta’mirda'), ('defect', 'Brak')], db_index=True, default='free', max_length=20),
        ),
    ]
