# Generated by Django 5.2.9 on 2026-03-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_client_rol_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='full',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
