# Generated by Django 5.2.9 on 2025-12-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_deed_status_alter_deedconsent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_boss',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
