# Generated by Django 5.2.9 on 2026-04-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_deed_code_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.DeleteModel(
            name='MaterialCategory',
        ),
    ]
