# Generated by Django 5.2.9 on 2026-04-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_material_category_delete_materialcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Lavozim', 'verbose_name_plural': 'Lavozim'},
        ),
    ]
