# Generated by Django 5.2.9 on 2026-03-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_goal_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='body',
            new_name='receiver_body',
        ),
        migrations.AddField(
            model_name='order',
            name='sender_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
