# Generated by Django 5.2.9 on 2025-12-29 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_employee_is_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('inventory', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('technics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.technics')),
            ],
            options={
                'verbose_name': 'Manitor',
                'verbose_name_plural': 'Manitorlar',
                'db_table': 'manitor',
            },
        ),
    ]
