# Generated by Django 5.2.9 on 2025-12-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_manitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='manitor',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('free', "Bo'sh"), ('repair', 'Ta’mirda'), ('defect', 'Brak')], db_index=True, default='free', max_length=20),
        ),
    ]
