# Generated by Django 5.2.9 on 2026-04-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_rank_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
