# Generated by Django 5.2.9 on 2026-03-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_body_order_receiver_body_order_sender_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('viewed', 'Yangi'), ('accepted', 'Jarayonda'), ('finished', 'Yakunlandi'), ('approved', 'Tasdiqlash kutulmoqda'), ('rejected', 'Rad etildi')], db_index=True, default='viewed', max_length=20),
        ),
    ]
