# Generated by Django 5.2.9 on 2025-12-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_manitor_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manitor',
            new_name='ExtraManitor',
        ),
        migrations.AlterModelOptions(
            name='extramanitor',
            options={'verbose_name': "Qo'shimcha texnika", 'verbose_name_plural': "Qo'shimcha texnikalar"},
        ),
        migrations.AlterModelTable(
            name='extramanitor',
            table='extratanitor',
        ),
    ]
