# Generated by Django 5.2.9 on 2026-04-29 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_technics_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaterial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordermaterial_user', to='main.employee'),
        ),
    ]
