# Generated by Django 5.2.9 on 2025-12-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_manitor_extramanitor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraManitor',
            new_name='ExtraTechnics',
        ),
    ]
