# Generated by Django 5.2.9 on 2026-03-31 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='receiver_body',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_body',
        ),
    ]
