# Generated by Django 5.2.9 on 2025-12-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_extramanitor_extratechnics'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratechnics',
            name='body',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extratechnics',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extratechnics',
            name='moc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extratechnics',
            name='parametr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratechnics',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
