# Generated by Django 5.2.9 on 2026-04-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_receiver_body_order_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='client',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
