# Generated by Django 5.2.9 on 2026-05-13 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_material_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='organization',
        ),
    ]
