# Generated by Django 5.2.9 on 2026-05-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_goal_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
