# Generated by Django 5.2.9 on 2025-12-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_extratechnics_body_extratechnics_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('free', "Bo'sh"), ('repair', 'Ta’mirda'), ('defect', 'Brak')], db_index=True, default='active', max_length=20),
        ),
    ]
