# Generated by Django 5.2.9 on 2026-05-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_organization_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region'),
        ),
    ]
