# Generated by Django 5.2.9 on 2026-01-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_material_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='inventory',
        ),
    ]
