# Generated by Django 5.2.9 on 2026-05-21 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_department_code_directorate_code_division_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region'),
        ),
    ]
