# Generated by Django 5.2.9 on 2026-01-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_material_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technics',
            name='number',
        ),
    ]
