# Generated by Django 5.2.9 on 2026-05-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_department_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='region',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
