# Generated by Django 5.2.9 on 2026-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_technics_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
