# Generated by Django 5.2.9 on 2026-05-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rol_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region'),
        ),
    ]
