# Generated by Django 5.2.9 on 2026-05-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_structure_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
