# Generated by Django 5.2.9 on 2026-01-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_technics_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extratechnics',
            name='number',
        ),
    ]
