# Generated by Django 5.2.9 on 2026-01-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_extratechnics_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
