# Generated by Django 5.2.9 on 2026-05-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_department_name_alter_directorate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
