# Generated by Django 5.2.9 on 2026-01-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_material_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='technics',
        ),
        migrations.AlterField(
            model_name='extratechnics',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
