# Generated by Django 5.2.9 on 2026-05-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_department_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
