# Generated by Django 5.2.9 on 2026-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
