# Generated by Django 5.2.9 on 2026-01-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_material_technics_alter_extratechnics_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technics',
            old_name='moc',
            new_name='mac',
        ),
        migrations.RemoveField(
            model_name='extratechnics',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='extratechnics',
            name='moc',
        ),
        migrations.AlterField(
            model_name='extratechnics',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='technics',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
