# Generated by Django 5.2.9 on 2026-01-14 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_moc_technics_mac_remove_extratechnics_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization'),
        ),
    ]
