# Generated by Django 5.2.9 on 2026-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_technics_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('free', "Bo'sh"), ('repair', 'Ta’mirda'), ('defect', 'Brak')], db_index=True, default='free', max_length=20),
        ),
    ]
