# Generated by Django 5.2.9 on 2026-06-09 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_department_name_alter_directorate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('created', "Qo'shildi"), ('edited', 'Taxrirlandi'), ('deleted', "O'chirildi"), ('assigned', 'Biriktirildi')], db_index=True, default='created', max_length=20)),
                ('body', models.TextField(blank=True, null=True)),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_received', to='main.employee')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.material')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_created', to='main.employee')),
            ],
            options={
                'verbose_name': 'Material harakati',
                'verbose_name_plural': 'Material harakatlari',
                'db_table': 'material_movement',
                'ordering': ['-date_creat'],
            },
        ),
    ]
