# Generated by Django 5.2.9 on 2026-06-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_materialmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmovement',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
