# Generated by Django 5.2.9 on 2026-01-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_technics_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='receiver_qr_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deed',
            name='sender_qr_done',
            field=models.BooleanField(default=False),
        ),
    ]
