# Generated by Django 5.2.9 on 2026-01-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_deed_receiver_qr_done_deed_sender_qr_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deed',
            old_name='receiver_qr_done',
            new_name='receiver_qr',
        ),
        migrations.RenameField(
            model_name='deed',
            old_name='sender_qr_done',
            new_name='sender_qr',
        ),
    ]
