# Generated by Django 5.2.9 on 2026-06-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_organization_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='region',
        ),
    ]
