# Generated by Django 5.2.9 on 2026-01-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_receiver_qr_done_deed_receiver_qr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deed',
            name='status',
        ),
        migrations.AlterField(
            model_name='deed',
            name='receiver_qr',
            field=models.CharField(choices=[('viewed', 'Kutulmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='viewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='deed',
            name='sender_qr',
            field=models.CharField(choices=[('viewed', 'Kutulmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='viewed', max_length=20),
        ),
    ]
