# Generated by Django 5.2.9 on 2026-06-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_organization_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='status',
        ),
    ]
