# Generated by Django 5.2.9 on 2026-01-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_deed_status_alter_deed_receiver_qr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deed',
            old_name='receiver_qr',
            new_name='status_receiver',
        ),
        migrations.RenameField(
            model_name='deed',
            old_name='sender_qr',
            new_name='status_sender',
        ),
    ]
