# Generated by Django 5.2.9 on 2026-06-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_material_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialmovement',
            old_name='number',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='income',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='outcome',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
