# Generated by Django 5.2.9 on 2026-01-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_receiver_qr_deed_status_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
    ]
