# Generated by Django 5.2.9 on 2026-06-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_number_materialmovement_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='status',
            field=models.CharField(choices=[('document', 'Dalolatnoma'), ('sendor', 'Yakuniy hisobot'), ('reestr', 'Reestr'), ('act', 'Akt')], db_index=True, default='act', max_length=20),
        ),
    ]
