# Generated by Django 5.2.9 on 2026-06-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_deed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deed',
            name='status',
            field=models.CharField(choices=[('document', 'Dalolatnoma'), ('svod', 'Yakuniy hisobot'), ('reestr', 'Reestr'), ('act', 'Akt')], db_index=True, default='act', max_length=20),
        ),
    ]
