# Generated by Django 5.2.9 on 2026-01-20 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_employee_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_boss', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'rol',
                'db_table': 'rol',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_boss',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.rol'),
        ),
    ]
