# Generated by Django 5.2.9 on 2026-01-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rol_remove_employee_is_boss_remove_employee_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='name',
        ),
        migrations.AddField(
            model_name='rol',
            name='is_shop',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
