# Generated by Django 5.2.9 on 2026-06-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_deed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deed',
            name='file_type',
        ),
    ]
