# Generated by Django 5.2.9 on 2026-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_deed_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='document',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
