# Generated by Django 5.2.9 on 2026-01-20 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_rol_name_rol_is_shop_rol_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='status',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rol',
        ),
        migrations.AddField(
            model_name='rol',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
    ]
