# Generated by Django 5.2.9 on 2026-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rol_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='order_edit',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
