# Generated by Django 5.2.9 on 2026-01-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_status_rol_client_remove_employee_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='is_barn',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
