# Generated by Django 5.2.9 on 2026-01-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_status_rol_client_remove_employee_rol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='is_boss',
            new_name='barn',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='is_shop',
            new_name='boss',
        ),
        migrations.AddField(
            model_name='rol',
            name='shop',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
