# Generated by Django 5.2.9 on 2026-01-20 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_is_boss_rol_barn_rename_is_shop_rol_boss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='main.employee'),
        ),
    ]
