# Generated by Django 5.2.9 on 2026-07-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rol_order_edit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='body',
            new_name='message_receiver',
        ),
        migrations.AddField(
            model_name='order',
            name='message_sender',
            field=models.TextField(blank=True, null=True),
        ),
    ]
