# Generated by Django 5.2.9 on 2026-07-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_rename_body_order_message_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedconsent',
            name='status',
            field=models.CharField(choices=[('viewed', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='viewed', max_length=20),
        ),
    ]
