# Generated by Django 5.2.9 on 2026-01-20 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_rol_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
    ]
