# Generated by Django 5.2.9 on 2026-01-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_rename_is_barn_rol_barn_rename_is_boss_rol_boss_and_more'),
        ('main', '0041_alter_rol_employee'),
    ]

    operations = [
    ]
