# Generated by Django 5.2.9 on 2026-07-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_deedconsent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='main.order'),
        ),
        migrations.AlterField(
            model_name='deed',
            name='status',
            field=models.CharField(choices=[('document', 'Dalolatnoma'), ('svod', 'Yakuniy hisobot'), ('reestr', 'Reestr'), ('act', 'Akt'), ('petition', 'Talabnoma')], db_index=True, default='act', max_length=20),
        ),
    ]
