# Generated by Django 5.2.9 on 2026-01-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_rol_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='akt',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
