# Generated by Django 5.2.9 on 2026-01-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_rol_akt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
    ]
