# Generated by Django 5.2.9 on 2026-01-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_merge_20260120_1521'),
        ('main', '0042_rol_akt'),
    ]

    operations = [
    ]
