# Generated by Django 5.2.9 on 2026-07-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_goal_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='organization',
        ),
        migrations.AddField(
            model_name='order',
            name='message_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('atm', 'ATMga ariza'), ('barn', 'Omborga ariza')], db_index=True, default='atm', max_length=20),
        ),
    ]
