# Generated by Django 5.2.9 on 2026-07-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_order_organization_order_message_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AddField(
            model_name='goal',
            name='type',
            field=models.CharField(choices=[('atm', 'ATMga ariza'), ('barn', 'Omborga ariza')], db_index=True, default='atm', max_length=20),
        ),
    ]
