# Generated by Django 5.2.9 on 2026-01-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_merge_0042_merge_20260120_1521_0042_rol_akt'),
        ('main', '0045_remove_employee_slug'),
    ]

    operations = [
    ]
