# Generated by Django 5.2.9 on 2026-01-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='date_receiver',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deed',
            name='date_sender',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
