# Generated by Django 5.2.9 on 2026-07-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_order_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liable',
            options={'verbose_name': 'xodimlar kategoriyasi', 'verbose_name_plural': 'xodimlar kategoriyasi'},
        ),
    ]
