# Generated by Django 5.2.9 on 2026-01-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_deed_date_receiver_deed_date_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='message_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deed_user', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='deed',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deed_received', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='deed',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deed_sender', to='main.employee'),
        ),
    ]
