# Generated by Django 5.2.9 on 2026-01-21 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_deed_message_user_deed_user_alter_deed_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deed',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deed_received', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='deed',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deed_sender', to='main.employee'),
        ),
    ]
