# Generated by Django 5.2.9 on 2026-07-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_liable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.goal')),
            ],
            options={
                'verbose_name': 'xodimlar ariza kategoriyasi',
                'verbose_name_plural': 'xodimlar ariza kategoriyasi',
                'db_table': 'OrderGoal',
            },
        ),
    ]
