# Generated by Django 5.2.9 on 2026-01-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_merge_20260120_1656'),
        ('main', '0047_deed_message_user_deed_user_alter_deed_receiver_and_more'),
    ]

    operations = [
    ]
