# Generated by Django 5.2.9 on 2026-01-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_deed_receiver_alter_deed_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='gdrive_file_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
