# Generated by Django 5.2.9 on 2026-07-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_ordergoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='user',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
