# Generated by Django 5.2.9 on 2026-01-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_deed_receiver_alter_deed_sender'),
        ('main', '0048_merge_20260120_2008'),
    ]

    operations = [
    ]
