# Generated by Django 5.2.9 on 2026-07-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_materialcategory_material_category_materialemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='organization',
        ),
        migrations.AddField(
            model_name='goal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('worker ', "(xizmat ko'rsatuvchi)"), ('client', 'Mijoz tashkilot')], db_index=True, default='client', max_length=10),
        ),
    ]
