# Generated by Django 5.2.9 on 2026-01-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_googledrivecredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deed',
            name='gdrive_file_id',
        ),
        migrations.DeleteModel(
            name='GoogleDriveCredential',
        ),
    ]
