# Generated by Django 5.2.9 on 2026-07-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_goal_type_remove_order_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='org_type',
            new_name='type',
        ),
    ]
