# Generated by Django 5.2.9 on 2026-01-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_deed_gdrive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
