# Generated by Django 5.2.9 on 2026-01-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_deed_html_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deed',
            name='html_content',
        ),
    ]
