# Generated by Django 5.2.9 on 2026-07-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_rename_org_type_organization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('worker', "(xizmat ko'rsatuvchi)"), ('client', 'Mijoz tashkilot')], db_index=True, default='client', max_length=10),
        ),
    ]
