# Generated by Django 5.2.9 on 2026-02-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_deed_html_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='barn',
            new_name='barn_mat',
        ),
        migrations.AddField(
            model_name='rol',
            name='barn_tex',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
