# Generated by Django 5.2.9 on 2026-07-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_organization_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('confirm_order', 'Arizani tasdiqlash')], 'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
    ]
