# Generated by Django 5.2.9 on 2026-07-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('all_organization', "Barcha tashkilotni ko'rish")], 'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'permissions': [('all_region', "Barcha tashkilotni ko'rish")], 'verbose_name': 'Xudud', 'verbose_name_plural': 'Xududlar'},
        ),
    ]
