# Generated by Django 5.2.9 on 2026-02-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_rename_barn_rol_barn_mat_rol_barn_tex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='barn_mat',
            new_name='barn',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='barn_tex',
        ),
    ]
