# Generated by Django 5.2.9 on 2026-07-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_organization_options_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'permissions': [('all_region', "Barcha Xududlarni ko'rish")], 'verbose_name': 'Xudud', 'verbose_name_plural': 'Xududlar'},
        ),
    ]
