# Generated by Django 5.2.9 on 2026-02-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_rename_barn_rol_barn_mat_rol_barn_tex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='barn_mat',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='barn_tex',
            new_name='material_edit',
        ),
        migrations.AddField(
            model_name='rol',
            name='technics',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='technics_edit',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
