# Generated by Django 5.2.9 on 2026-07-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('boss_employee', "Departamentiga tegishli texnikalarni ko'rish"), ('shop_employee', 'Materialga javobgar shaxs'), ('status_employee', "Statistikani ko'rish")], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
    ]
