# Generated by Django 5.2.9 on 2026-02-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_merge_20260121_1100'),
        ('main', '0057_rename_barn_mat_rol_material_and_more'),
    ]

    operations = [
    ]
