# Generated by Django 5.2.9 on 2026-02-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_rename_barn_mat_rol_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='org_type',
        ),
    ]
