# Generated by Django 5.2.9 on 2026-07-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_employee_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
