# Generated by Django 5.2.9 on 2026-07-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_delete_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_chat',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram chat ID'),
        ),
    ]
