# Generated by Django 5.2.9 on 2026-02-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_merge_20260202_1027'),
    ]

    operations = []
