# Generated by Django 5.2.9 on 2026-02-04 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_remove_organization_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technics',
            name='body',
        ),
        migrations.AddField(
            model_name='technics',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.department'),
        ),
        migrations.AlterField(
            model_name='technics',
            name='status',
            field=models.CharField(choices=[('free', "Bo'sh"), ('active', 'Aktiv'), ('repair', 'Ta’mirda'), ('defect', 'Yaroqsiz')], db_index=True, default='free', max_length=20),
        ),
    ]
