# Generated by Django 5.2.9 on 2026-02-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_remove_technics_body_technics_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extratechnics',
            name='body',
        ),
        migrations.RemoveField(
            model_name='material',
            name='body',
        ),
        migrations.RemoveField(
            model_name='material',
            name='unit',
        ),
        migrations.AlterField(
            model_name='extratechnics',
            name='status',
            field=models.CharField(choices=[('free', "Bo'sh"), ('active', 'Aktiv'), ('repair', 'Ta’mirda'), ('defect', 'Yaroqsiz')], db_index=True, default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('free', "Bo'sh"), ('active', 'Aktiv'), ('repair', 'Ta’mirda'), ('defect', 'Yaroqsiz')], db_index=True, default='free', max_length=20),
        ),
    ]
