# Generated by Django 5.2.9 on 2026-02-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_remove_organization_is_active_and_more'),
        ('main', '0059_remove_rol_barn'),
    ]

    operations = [
    ]
