# Generated by Django 5.2.9 on 2026-07-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_employee_telegram_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'permissions': [('all_material_employee', "Barcha xodimlarni ko'rish")], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiallar'},
        ),
    ]
