# Generated by Django 6.0.7 on 2026-07-23 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_material_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contract'),
        ),
    ]
