# Generated by Django 5.2.9 on 2026-02-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_remove_technics_body_technics_department_and_more'),
        ('main', '0060_merge_20260204_1146'),
    ]

    operations = [
    ]
