# Generated by Django 5.2.9 on 2026-02-04 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_remove_extratechnics_body_remove_material_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'birligi',
                'verbose_name_plural': 'birligi',
                'db_table': 'unit',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.unit'),
        ),
    ]
