# Generated by Django 5.2.9 on 2026-02-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_unit_material_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
