# Generated by Django 5.2.9 on 2026-02-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_remove_extratechnics_body_remove_material_body_and_more'),
        ('main', '0061_merge_20260204_1152'),
    ]

    operations = [
    ]
