# Generated by Django 5.2.9 on 2026-02-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_remove_goal_topic_delete_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type_of_work',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_receiver', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_sender', to='main.employee'),
        ),
    ]
