# Generated by Django 5.2.9 on 2026-02-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_unit_material_unit'),
        ('main', '0062_merge_20260204_1210'),
    ]

    operations = [
    ]
