# Generated by Django 5.2.9 on 2026-02-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_remove_order_type_of_work_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaterial',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order'),
        ),
    ]
