# Generated by Django 5.2.9 on 2026-07-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='user_edit',
            field=models.BooleanField(default=True),
        ),
    ]
