# Generated by Django 5.2.9 on 2026-02-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_remove_goal_topic_delete_topic'),
        ('main', '0063_merge_20260204_1240'),
    ]

    operations = [
    ]
