# Generated by Django 5.2.9 on 2026-02-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_ordermaterial_order'),
        ('main', '0064_merge_20260204_1243'),
    ]

    operations = [
    ]
