# Generated by Django 5.2.9 on 2026-02-04 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_ordermaterial_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='receiver_seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deed',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deed_receiver', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='deed',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deed_sender', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='deed',
            name='sender_seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deed_user', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='deedconsent',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee'),
        ),
    ]
