# Generated by Django 5.2.9 on 2026-07-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_deed_user_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialmovement',
            name='balance',
        ),
    ]
