# Generated by Django 5.2.9 on 2026-02-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_deed_receiver_seen_alter_deed_receiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
