# Generated by Django 5.2.9 on 2026-07-28 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_remove_materialmovement_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization'),
        ),
    ]
