# Generated by Django 5.2.9 on 2026-02-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_delete_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.BooleanField(db_index=True, default=False)),
                ('boss', models.BooleanField(db_index=True, default=False)),
                ('shop', models.BooleanField(db_index=True, default=False)),
                ('akt', models.BooleanField(db_index=True, default=False)),
                ('technics', models.BooleanField(db_index=True, default=False)),
                ('technics_edit', models.BooleanField(db_index=True, default=False)),
                ('material', models.BooleanField(db_index=True, default=False)),
                ('material_edit', models.BooleanField(db_index=True, default=False)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'rol',
                'db_table': 'rol',
            },
        ),
    ]
