# Generated by Django 5.2.9 on 2026-08-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_deed_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
