# Generated by Django 5.2.9 on 2026-02-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_delete_rol'),
        ('main', '0066_merge_20260204_1247'),
    ]

    operations = [
    ]
