# Generated by Django 5.2.9 on 2026-02-05 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaterial',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='main.order'),
        ),
    ]
