# Generated by Django 5.2.9 on 2026-02-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_ordermaterial_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contract',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
