# Generated by Django 5.2.9 on 2026-02-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_ordermaterial_order'),
        ('main', '0068_rol'),
    ]

    operations = [
    ]
