# Generated by Django 5.2.9 on 2026-02-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_merge_0068_alter_ordermaterial_order_0068_rol'),
        ('main', '0069_organization_contract'),
    ]

    operations = [
    ]
