# Generated by Django 5.2.9 on 2026-02-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_organization_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='index',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='order',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
