# Generated by Django 5.2.9 on 2026-08-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_employee_options_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('boss_employee', "Departamentiga tegishli texnikalarni ko'rish"), ('shop_employee', 'Materialga javobgar shaxs'), ('status_employee', "Statistikani ko'rish"), ('permission_employee', 'Xodimlarga ruxsatlarni berish')], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'permissions': [('all_material_employee', "Barcha xodimlarni ko'rish")], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiallar'},
        ),
    ]
