# Generated by Django 5.2.9 on 2026-02-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_merge_20260205_1754'),
        ('main', '0070_rol_index_rol_order'),
    ]

    operations = [
    ]
