# Generated by Django 5.2.9 on 2026-02-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_rol_index_rol_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
