# Generated by Django 5.2.9 on 2026-08-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_employee_options_alter_material_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
