# Generated by Django 5.2.9 on 2026-02-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_deed_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyMCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akt_body', models.TextField(blank=True, null=True)),
                ('svod_body', models.TextField(blank=True, null=True)),
                ('reestr_body', models.TextField(blank=True, null=True)),
                ('docx_body', models.TextField(blank=True, null=True)),
                ('akt_all_body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
