# Generated by Django 5.2.9 on 2026-08-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_technics_is_online'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('boss_employee', "Departamentiga tegishli texnikalarni ko'rish"), ('shop_employee', 'Materialga javobgar shaxs'), ('status_employee', "Statistikani ko'rish"), ('permission_employee', 'Xodimlarga ruxsatlarni berish'), ('report_employee', "Hisobotlarni ko'rish")], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
    ]
