# Generated by Django 5.2.9 on 2026-02-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_tinymce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinymce',
            old_name='akt_all_body',
            new_name='akt',
        ),
        migrations.RenameField(
            model_name='tinymce',
            old_name='akt_body',
            new_name='akt_all',
        ),
        migrations.RenameField(
            model_name='tinymce',
            old_name='docx_body',
            new_name='docx',
        ),
        migrations.RenameField(
            model_name='tinymce',
            old_name='reestr_body',
            new_name='reestr',
        ),
        migrations.RenameField(
            model_name='tinymce',
            old_name='svod_body',
            new_name='svod',
        ),
    ]
