# Generated by Django 5.2.9 on 2026-09-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='deeds', to='main.order'),
        ),
    ]
