# Generated by Django 5.2.9 on 2026-02-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_rename_akt_all_body_tinymce_akt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinymce',
            old_name='akt',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='tinymce',
            name='akt_all',
        ),
        migrations.RemoveField(
            model_name='tinymce',
            name='docx',
        ),
        migrations.RemoveField(
            model_name='tinymce',
            name='reestr',
        ),
        migrations.RemoveField(
            model_name='tinymce',
            name='svod',
        ),
        migrations.AddField(
            model_name='tinymce',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
