# Generated by Django 5.2.9 on 2026-09-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_deed_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deed',
            name='order',
        ),
    ]
