# Generated by Django 5.2.9 on 2026-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_remove_deed_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
