# Generated by Django 5.2.9 on 2026-02-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_rename_akt_tinymce_body_remove_tinymce_akt_all_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TinyMCE',
        ),
    ]
