# Generated by Django 5.2.9 on 2026-02-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_delete_tinymce'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='file_type',
            field=models.BooleanField(default=False),
        ),
    ]
