# Generated by Django 5.2.9 on 2026-09-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_alter_technics_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization'),
        ),
    ]
