# Generated by Django 5.2.9 on 2026-02-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_merge_20260209_1113'),
        ('main', '0076_deed_file_type'),
    ]

    operations = [
    ]
