# Generated by Django 5.2.9 on 2026-02-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_deed_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratechnics',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technics',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
