# Generated by Django 5.2.9 on 2026-09-21 11:29

import django.db.models.deletion
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_materialcategory_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deed/', validators=[main.validators.validate_attachment_extension])),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('deed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.deed')),
            ],
            options={
                'verbose_name': 'Xujat ilovasi',
                'verbose_name_plural': 'Xujatlar ilovasi',
                'db_table': 'deedfiles',
            },
        ),
    ]
