# Generated by Django 5.2.9 on 2026-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_extratechnics_is_active_material_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
