# Generated by Django 5.2.9 on 2026-02-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_extratechnics_is_active_material_is_active_and_more'),
        ('main', '0077_merge_0071_merge_20260209_1113_0076_deed_file_type'),
    ]

    operations = [
    ]
