# Generated by Django 5.2.9 on 2026-09-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_deedfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmovement',
            name='status',
            field=models.CharField(choices=[('created', "Qo'shildi"), ('edited', 'Taxrirlandi'), ('deleted', "O'chirildi"), ('assigned', 'Biriktirildi'), ('order', 'Ariza orqali berildi')], db_index=True, default='created', max_length=20),
        ),
    ]
