# Generated by Django 5.2.9 on 2026-02-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_merge_20260224_1530'),
        ('main', '0078_rol_status'),
    ]

    operations = [
    ]
