# Generated by Django 5.2.9 on 2026-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_alter_materialmovement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'permissions': [('all_material_employee', "Barcha xodimlarni ko'rish"), ('material_service', 'Material sarflash')], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiallar'},
        ),
        migrations.AlterField(
            model_name='materialmovement',
            name='status',
            field=models.CharField(choices=[('created', "Qo'shildi"), ('edited', 'Taxrirlandi'), ('deleted', "O'chirildi"), ('assigned', 'Biriktirildi'), ('order', 'Ariza orqali berildi'), ('service', 'Xizmat ko‘rsatildi')], db_index=True, default='created', max_length=20),
        ),
    ]
