# Generated by Django 5.2.9 on 2026-02-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_rol_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratechnics',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization'),
        ),
    ]
