# Generated by Django 5.2.9 on 2026-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_alter_material_options_alter_materialmovement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deed',
            name='status',
            field=models.CharField(choices=[('document', 'Dalolatnoma'), ('svod', 'Yakuniy hisobot'), ('reestr', 'Reestr'), ('act', 'Akt'), ('petition', 'Talabnoma'), ('service', 'Sarf material')], db_index=True, default='act', max_length=20),
        ),
    ]
