# Generated by Django 5.2.9 on 2026-03-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_extratechnics_organization'),
        ('main', '0079_merge_0078_merge_20260224_1530_0078_rol_status'),
    ]

    operations = [
    ]
