# Generated by Django 5.2.9 on 2026-03-03 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_extratechnics_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.directorate'),
        ),
        migrations.AddField(
            model_name='technics',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.division'),
        ),
    ]
