# Generated by Django 5.2.9 on 2026-03-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_merge_20260302_0924'),
        ('main', '0080_technics_directorate_technics_division'),
    ]

    operations = [
    ]
