# Generated by Django 5.2.9 on 2026-03-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_technics_directorate_technics_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='index',
        ),
    ]
