# Generated by Django 5.2.9 on 2026-03-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_merge_20260303_1420'),
        ('main', '0081_remove_rol_index'),
    ]

    operations = [
    ]
