# Generated by Django 5.2.9 on 2026-03-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_merge_0081_merge_20260303_1420_0081_remove_rol_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='order',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
