# Generated by Django 5.2.9 on 2026-03-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_contract_liable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='liable',
            table='Liable',
        ),
    ]
