# Generated by Django 5.2.9 on 2026-03-10 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_alter_liable_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': "Qo'shimcha kategoriya",
                'verbose_name_plural': "Qo'shimcha kategoriyalar",
                'db_table': 'extracategory',
            },
        ),
        migrations.AlterModelTable(
            name='extratechnics',
            table='extratechnics',
        ),
        migrations.AddField(
            model_name='extratechnics',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.extracategory'),
        ),
    ]
