# Generated by Django 5.2.9 on 2026-03-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_contract_liable'),
        ('main', '0083_rol_order_rol_status'),
    ]

    operations = [
    ]
