# Generated by Django 5.2.9 on 2026-03-13 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_extracategory_alter_extratechnics_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('viewed', 'Yangi'), ('accepted', 'Jarayonda'), ('finished', 'Yakunlandi'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='viewed', max_length=20),
        ),
    ]
