# Generated by Django 5.2.9 on 2026-03-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_alter_liable_table'),
        ('main', '0084_merge_0082_contract_liable_0083_rol_order_rol_status'),
    ]

    operations = [
    ]
