# Generated by Django 5.2.9 on 2026-03-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_deed_uuid_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deed',
            name='uuid',
        ),
        migrations.AddField(
            model_name='deed',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
    ]
