# Generated by Django 5.2.9 on 2026-03-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_extracategory_alter_extratechnics_table_and_more'),
        ('main', '0085_merge_20260306_1304'),
    ]

    operations = [
    ]
