# Generated by Django 5.2.9 on 2026-03-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_remove_deed_uuid_deed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qk/'),
        ),
        migrations.AlterField(
            model_name='deed',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
