# Generated by Django 5.2.9 on 2026-03-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_merge_20260313_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('viewed', 'Yangi'), ('accepted', 'Jarayonda'), ('finished', 'Yakunlandi'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='viewed', max_length=20),
        ),
    ]
