# Generated by Django 5.2.9 on 2026-03-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_deed_code_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deed',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
