# Generated by Django 5.2.9 on 2026-03-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_technics_qr_code_alter_deed_code'),
        ('main', '0088_alter_deed_code'),
    ]

    operations = [
    ]
