# Generated by Django 5.2.9 on 2026-03-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_materialcategory_material_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'verbose_name': 'MaterialCategory', 'verbose_name_plural': 'MaterialCategorylat'},
        ),
    ]
