# Generated by Django 5.2.9 on 2026-03-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_alter_deed_code'),
        ('main', '0090_alter_materialcategory_options'),
    ]

    operations = [
    ]
