# Generated by Django 5.2.9 on 2026-10-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_remove_old_goal_receiver_matcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='receiver_can_add_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deed',
            name='sender_can_add_consent',
            field=models.BooleanField(default=False),
        ),
    ]
