# Generated by Django 5.2.9 on 2026-03-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_merge_20260318_1609'),
    ]

    operations = [
    ]
