# Generated by Django 5.2.9 on 2026-03-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_merge_20260318_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraCategory',
            new_name='StructureCategory',
        ),

        migrations.RenameModel(
            old_name='ExtraTechnics',
            new_name='Structure',
        ),

        migrations.AlterModelTable(
            name='structurecategory',
            table='structurecategory',
        ),

        migrations.AlterModelTable(
            name='structure',
            table='structure',
        ),

        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='directorate',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='division',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),

        migrations.AddField(
            model_name='technics',
            name='group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='main.group',
            ),
        ),

        migrations.AlterField(
            model_name='structure',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='main.structurecategory',
            ),
        ),
    ]