# Generated by Django 5.2.9 on 2026-10-08 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_deed_signer_can_add_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_region',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.region'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_department',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.department'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_organization',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_region',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.region'),
        ),
    ]
