# Generated by Django 5.2.9 on 2026-03-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_structurecategory_delete_extracategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deed',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deedconsent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='directorate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='liable',
            options={},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ordermaterial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={},
        ),
        migrations.AlterModelOptions(
            name='structurecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='technics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.RemoveField(
            model_name='structurecategory',
            name='slug',
        ),
    ]
