# Generated by Django 5.2.9 on 2026-10-08 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_backfill_order_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmovement',
            name='material_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='material_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='unit_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='user_organization',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.organization'),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='user_region',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.region'),
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='material_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='material_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ordermaterial',
            name='unit_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
    ]
