# Generated by Django 5.2.9 on 2026-10-08 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_backfill_price_unit_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deed',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deed_receiver', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='deed',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deed_sender', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='deed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deed_user', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='material',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.employee'),
        ),
        migrations.AlterField(
            model_name='materialmovement',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_received', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='materialmovement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_created', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_receiver', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_sender', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_user', to='main.employee'),
        ),
    ]
