# Generated by Django 5.2.9 on 2026-10-08 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_protect_history_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='user_region',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.region'),
        ),
    ]
